### ISSUE TITLE
You demo static URL/QR code, so how about getting the dynamic ones?

### ISSUE THREAD

**Issue by Port2** [SnowCait/qrcode#2]
Your example is for static URL? How can I pass dynamic content obtained in GitHub actions to this action and get a dynamic QR code?

**Comment by SnowCait** [comment]
You can use `${{ }}` as same as other actions.

```yml
name: QRCode PR
on:
  pull_request:
    types: [ opened ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: SnowCait/qrcode@v1.0.0
      with:
        text: ${{ github.event.pull_request.html_url }}
        path: qrcode.png
```
